### PR TITLE
Update `update.py` for Pydantic 2

### PR DESCRIPTION
**Pull request by jwodder**

### CODE REVIEW

**Comment by yarikoptic** [comment]
Let's see what happens now given that https://github.com/datalad/git-annex/pull/184 was merged.

Thank you @jwodder

**Comment by jwodder** [comment]
@yarikoptic datalad/git-annex#184 has nothing to do with this.  That PR is for deployment of the `clients/` directory in datalad/git-annex.  This PR is for the script in datalad/git-annex-ci-client-jobs that processes results from the clients.

**Comment by yarikoptic** [comment]
ah, ok. any manual upgrades to be done?

**Comment by jwodder** [comment]
@yarikoptic No.  This script is only "deployed" by being run inside GitHub Actions.

**Pull request merged**
